// Restaurant Database
// Scalable structure supporting 1000+ restaurants

const restaurantData = [
// Existing restaurants (1-24)
{
    id: 1,
    name: "Sweet Maple",
    location: "bay-area",
    status: "togo",
    occasion: "brunch",
    cuisine: "asian-fusion",
    price: "$$",
    rating: 4.4,
    reviewCount: 940,
    tags: ["Palo Alto", "Asian Fusion", "Brunch"],
    address: "150 University Ave, Palo Alto",
    phone: "(650) 521-0764",
    occasionLabel: "Brunch, Date, Friends",
    capacity: "2-6 people",
    dishes: ["Millionaire's Bacon", "Chicken Croffle", "Ube Latte", "Matcha Moffle"],
    booking: "Walk-in only. Arrive before 8:30am on weekends or wait 1-2 hours.",
    reviews: [
        {name: "Riyakan Kapoor", rating: 5, text: "Ultimate brunch spot! Ube Latte is the star. French Toast is the best I've ever had."},
        {name: "Shubham Kamdi", rating: 4, text: "High-energy modern brunch. Millionaire's Bacon is the main draw but pricey. Two people easily $100."},
        {name: "Hua Mao", rating: 5, text: "Super popular in downtown Palo Alto. American + Asian fusion. Huge portions, cozy decor."}
    ],
    heroImage: "images/sweet-maple-1.jpg",
    gallery: ["images/sweet-maple-2.jpg", "images/sweet-maple-3.jpg", "images/sweet-maple-4.jpg"],
    michelin: 0
},
{
    id: 2,
    name: "Sushi Shin",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "japanese",
    price: "$$$$$",
    rating: 4.4,
    reviewCount: 219,
    tags: ["Redwood City", "Omakase", "Michelin"],
    address: "312 Arguello St, Redwood City",
    phone: "(650) 921-8809",
    occasionLabel: "Special, Date, Celebration",
    capacity: "2-4 people",
    dishes: ["Omakase Menu", "Otoro", "Uni", "Lobster Spring Roll"],
    booking: "Reservations highly recommended. Book via website or call. Intimate seating, limited availability.",
    reviews: [
        {name: "Lin Sun-Hoffman", rating: 5, text: "Standout sushi experience! Intimate setting, elegant atmosphere. Chef Jason Zhan is masterful."},
        {name: "David Famero", rating: 5, text: "Unforgettable omakase! Impeccable cleanliness, quiet precision. Michelin star quality."},
        {name: "Michael Lyons", rating: 5, text: "Spectacular meal! Lobster spring roll and greeneye fish. Otoro and uni were amazing."}
    ],
    heroImage: "images/sushi-shin-1.jpg",
    gallery: ["images/sushi-shin-2.jpg", "images/sushi-shin-3.jpg", "images/sushi-shin-4.jpg"],
    michelin: 0
},
{
    id: 3,
    name: "Ping's Bistro 留湘",
    location: "bay-area",
    status: "tried",
    occasion: "date",
    cuisine: "chinese",
    price: "$$$",
    rating: 4.4,
    reviewCount: 194,
    tags: ["Cupertino", "Yunnan", "Dai Cuisine"],
    address: "10700 S De Anza Blvd, Cupertino",
    phone: "(408) 564-5134",
    occasionLabel: "Date, Family, Friends",
    capacity: "2-8 people",
    dishes: ["Dai Style Pork Ribs", "Grilled Fish with Lemongrass", "Boletus Fried Rice", "Wild Mushrooms with Pork"],
    booking: "Walk-in or call ahead. Arrive at 5pm opening or expect 1+ hour wait. 18% service charge.",
    reviews: [
        {name: "JP Figure", rating: 5, text: "Completely blown away by vibrant flavors! Authentic Yunnan and Dai-style cuisine."},
        {name: "Chelsea", rating: 5, text: "Every dish is CRAZY good! Osmanthus Honey Milk Jelly is the best dessert."},
        {name: "Kevin Kruemp", rating: 5, text: "Excellent restaurant! Food is very authentic and atmosphere is bright and inviting."}
    ],
    heroImage: "images/pings-bistro-1.jpg",
    gallery: ["images/pings-bistro-2.jpg", "images/pings-bistro-3.jpg", "images/pings-bistro-4.jpg"],
    michelin: 0,
    date: "2025-01-12"
},
{
    id: 4,
    name: "JiangNan Delicacy 江南雅厨",
    location: "bay-area",
    status: "togo",
    occasion: "date",
    cuisine: "chinese",
    price: "$$",
    rating: 4.1,
    reviewCount: 84,
    tags: ["Milpitas", "Jiangsu", "Suzhou"],
    address: "1750 N Milpitas Blvd, Milpitas",
    phone: "(669) 263-6115",
    occasionLabel: "Date, Family, Business",
    capacity: "2-8 people",
    dishes: ["Sweet & Sour Fish", "Sticky Rice Cake", "Braised River Eel", "Sweet Braised Lotus Roots"],
    booking: "Walk-in or call ahead. Reservations recommended weekends. Live traditional music select evenings.",
    reviews: [
        {name: "Mia Mi", rating: 5, text: "Viral on Red Note! Classy, delicate decoration. Artists playing traditional music."},
        {name: "Colleen Bei", rating: 5, text: "Wonderful dining experience! True taste of Suzhou cuisine!"},
        {name: "H. J.", rating: 3, text: "Nicely decorated, no wait. Food noticeably too sweet for our taste."}
    ],
    heroImage: "images/jiangnan-1.jpg",
    gallery: ["images/jiangnan-2.jpg", "images/jiangnan-3.jpg", "images/jiangnan-4.jpg"],
    michelin: 0
},
{
    id: 5,
    name: "Tai Er 太二酸菜鱼",
    location: "bay-area",
    status: "togo",
    occasion: "casual",
    cuisine: "chinese",
    price: "$$",
    rating: 4.1,
    reviewCount: 140,
    tags: ["San Mateo", "Sichuan", "Casual"],
    address: "98 E 4th Ave, San Mateo",
    phone: "(650) 398-2222",
    occasionLabel: "Casual, Friends, Family",
    capacity: "2-6 people",
    dishes: ["Signature Sauerkraut Fish", "Spicy Chili Chicken", "Spicy Wontons", "Crispy Calamari"],
    booking: "Reservations recommended. Gets crowded during dinner time.",
    reviews: [
        {name: "Steven Lin", rating: 5, text: "Sauerkraut Fish lives up to reputation - fish sliced with precision, deeply flavorful broth."},
        {name: "Priscilla Tang", rating: 5, text: "Pillow-soft fish with perfect Sichuan peppercorn 'ma'. Great for groups!"},
        {name: "Christopher Chung", rating: 5, text: "Instagramable and elevated. Signature Suancai fish is phenomenal."}
    ],
    heroImage: "images/tai-er-1.jpg",
    gallery: ["images/tai-er-2.jpg", "images/tai-er-3.jpg", "images/tai-er-4.jpg"],
    michelin: 0
},
{
    id: 6,
    name: "Sushi Yoshizumi",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "japanese",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 198,
    tags: ["San Mateo", "Japanese", "Special"],
    address: "325 E 4th Ave, San Mateo",
    phone: "(650) 348-8126",
    occasionLabel: "Special, Date, Omakase",
    capacity: "2-4 people",
    dishes: ["Edomae Omakase", "Hokkaido Uni", "Salt Water Eel", "Squid"],
    booking: "Reservations required. Only 8 seats. Book well in advance.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Cherished by expats. Chef Akira Yoshizumi perfected Edomae sushi style. Only 8 seats at the cypress bar."},
        {name: "SF Chronicle", rating: 5, text: "Hokkaido uni is musky and bright; apricot-colored spoonful served atop vinegared rice wrapped in crisp seaweed."}
    ],
    heroImage: "images/sushi-yoshizumi-1.jpg",
    gallery: ["images/sushi-yoshizumi-2.jpg", "images/sushi-yoshizumi-3.jpg", "images/sushi-yoshizumi-4.jpg"],
    michelin: 0
},
{
    id: 7,
    name: "Acquerello",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "italian",
    price: "$$$$$",
    rating: 4.6,
    reviewCount: 640,
    tags: ["San Francisco", "Italian", "Special"],
    address: "1722 Sacramento St, SF",
    phone: "(415) 567-5432",
    occasionLabel: "Special, Date, Anniversary",
    capacity: "2-6 people",
    dishes: ["Carrot & Ginger Terrine", "Handmade Pastas", "Cheese Plate", "Tasting Menu"],
    booking: "Reservations highly recommended. Tue-Sat dinner only.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Handmade pastas combine classic technique with personal style. Dishes arrive as visual masterpieces."},
        {name: "TripAdvisor", rating: 5, text: "The class of San Francisco and the pinnacle of Italian fine dining in the bay."}
    ],
    heroImage: "images/acquerello-1.jpg",
    gallery: ["images/acquerello-2.jpg", "images/acquerello-3.jpg", "images/acquerello-4.jpg"],
    michelin: 1
},
{
    id: 8,
    name: "Foreign Cinema",
    location: "sf",
    status: "togo",
    occasion: "date",
    cuisine: "american",
    price: "$$$",
    rating: 4.5,
    reviewCount: 3292,
    tags: ["San Francisco", "American", "Date Night"],
    address: "2534 Mission St, SF",
    phone: "(415) 648-7600",
    occasionLabel: "Date, Special, Unique",
    capacity: "2-6 people",
    dishes: ["Pork Chop", "Fresh Oysters", "Californian-Mediterranean", "Weekend Brunch"],
    booking: "Reservations recommended. Outdoor courtyard projects films nightly.",
    reviews: [
        {name: "The Infatuation", rating: 5, text: "Beyond watching movies - the food is just as memorable. Produce-heavy Californian dishes."}
    ],
    heroImage: "images/foreign-cinema-1.jpg",
    gallery: ["images/foreign-cinema-2.jpg", "images/foreign-cinema-3.jpg", "images/foreign-cinema-4.jpg"],
    michelin: 0
},
{
    id: 9,
    name: "I Shanghai Delight 阿拉上海",
    location: "bay-area",
    status: "togo",
    occasion: "casual",
    cuisine: "chinese",
    price: "$$",
    rating: 4.4,
    reviewCount: 1218,
    tags: ["Fremont", "Chinese", "Casual"],
    address: "6016 Stevenson Blvd, Fremont",
    phone: "(510) 709-1196",
    occasionLabel: "Family, Friends, Casual",
    capacity: "2-8 people",
    dishes: ["Xiao Long Bao", "Soup Dumplings", "Pan Fried Dumplings", "Wonton Soup"],
    booking: "Walk-in or call ahead. Wed closed. Multiple Bay Area locations.",
    reviews: [
        {name: "Yelp", rating: 5, text: "Most authentic soup dumplings. Every single dish was delicious!"},
        {name: "Customer", rating: 5, text: "I grew up in Shanghai and found this the most authentic Shanghainese cuisine."}
    ],
    heroImage: "images/i-shanghai-1.jpg",
    gallery: ["images/i-shanghai-2.jpg", "images/i-shanghai-3.jpg", "images/i-shanghai-4.jpg"],
    michelin: 0
},
{
    id: 10,
    name: "La Mar Cocina Peruana",
    location: "sf",
    status: "togo",
    occasion: "date",
    cuisine: "peruvian",
    price: "$$$",
    rating: 4.5,
    reviewCount: 4735,
    tags: ["San Francisco", "Peruvian", "Waterfront"],
    address: "Pier 1½ The Embarcadero, SF",
    phone: "(415) 397-8880",
    occasionLabel: "Date, Special, Waterfront",
    capacity: "2-8 people",
    dishes: ["Ceviche", "Lomo Saltado", "Arroz La Mar", "Pisco Sour", "Empanadas"],
    booking: "Reservations recommended. Waterfront at Pier 1½. Covered patio dining.",
    reviews: [
        {name: "Condé Nast", rating: 5, text: "Arroz la mar with shrimp, clams, mussels, calamari, and arborio rice."},
        {name: "TripAdvisor", rating: 5, text: "Fantastic fresh taro chips with dynamite green dipping sauce. Get the Pisco Sour!"}
    ],
    heroImage: "images/la-mar-1.jpg",
    gallery: ["images/la-mar-2.jpg", "images/la-mar-3.jpg", "images/la-mar-4.jpg"],
    michelin: 0
},
{
    id: 11,
    name: "Suppenküche",
    location: "sf",
    status: "togo",
    occasion: "casual",
    cuisine: "german",
    price: "$$",
    rating: 4.5,
    reviewCount: 1944,
    tags: ["San Francisco", "German", "Casual"],
    address: "525 Laguna St, SF (Hayes Valley)",
    phone: "(415) 252-9289",
    occasionLabel: "Casual, Friends, Brunch",
    capacity: "2-8 people",
    dishes: ["Wiener Schnitzel", "Brotwurst", "Schweinebraten", "Pretzel", "German Beer"],
    booking: "Walk-in or call ahead. Oktoberfest specials Sept 20 - Oct 5. Famous for 1-liter beer mugs.",
    reviews: [
        {name: "The Infatuation", rating: 5, text: "The best German food in town. Less 'how fast can you chug a beer' than Leopold's."},
        {name: "Yelp", rating: 5, text: "Traditional Bavarian Wirthaus dining. Warm atmosphere, specialty beer selection. Est. 1993."}
    ],
    heroImage: "images/suppenkuche-1.jpg",
    gallery: ["images/suppenkuche-2.jpg", "images/suppenkuche-3.jpg", "images/suppenkuche-4.jpg"],
    michelin: 0
},
{
    id: 12,
    name: "Shang Cafe",
    location: "bay-area",
    status: "togo",
    occasion: "casual",
    cuisine: "chinese",
    price: "$$",
    rating: 4.1,
    reviewCount: 553,
    tags: ["San Jose", "Chinese", "Sichuan"],
    address: "6154 Bollinger Rd, San Jose",
    phone: "(408) 320-2876",
    occasionLabel: "Casual, Friends, Family",
    capacity: "2-8 people",
    dishes: ["Spicy Fish Fillet", "Mapo Tofu", "Sichuan Chicken", "Braised Pork Belly", "Sichuan Cold Noodles"],
    booking: "Walk-in or call ahead. Wed closed. Lunch 11am-2pm, Dinner 5pm-8:15pm.",
    reviews: [
        {name: "Yelp", rating: 5, text: "Boiled Fish Fillet in Green Peppers Soup - relatively simple dishes but executed sooo well."},
        {name: "Reviewer", rating: 5, text: "Arguably one of the most authentic Sichuan spots in South Bay."}
    ],
    heroImage: "images/shang-cafe-1.jpg",
    gallery: ["images/shang-cafe-2.jpg", "images/shang-cafe-3.jpg", "images/shang-cafe-4.jpg"],
    michelin: 0
},
{
    id: 13,
    name: "Tony's Pizza Napoletana",
    location: "sf",
    status: "togo",
    occasion: "casual",
    cuisine: "italian",
    price: "$$",
    rating: 4.5,
    reviewCount: 9858,
    tags: ["San Francisco", "Italian", "Pizza"],
    address: "1570 Stockton St, SF (North Beach)",
    phone: "(415) 835-9888",
    occasionLabel: "Casual, Family, Pizza Night",
    capacity: "2-8 people",
    dishes: ["Margherita", "Neapolitan Pizza", "Sicilian Pizza", "New York Style"],
    booking: "Long lines expected. Join waitlist online. Daily 12pm-10pm.",
    reviews: [
        {name: "The Infatuation", rating: 5, text: "13-time World Pizza Champion Tony Gemignani. Tony's is impressive."},
        {name: "Yelp", rating: 5, text: "Several styles: Neapolitan, Classic American, Sicilian, Pizza Romana, New York, Detroit and St. Louis."}
    ],
    heroImage: "images/tonys-pizza-1.jpg",
    gallery: ["images/tonys-pizza-2.jpg", "images/tonys-pizza-3.jpg", "images/tonys-pizza-4.jpg"],
    michelin: 0
},
{
    id: 14,
    name: "Imperial Treasure",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "chinese",
    price: "$$$",
    rating: 4.1,
    reviewCount: 261,
    tags: ["Palo Alto", "Chinese", "Fine Dining"],
    address: "151 California Ave, Palo Alto",
    phone: "(650) 656-9597",
    occasionLabel: "Special, Business, Family",
    capacity: "2-10 people",
    dishes: ["Peking Duck", "Walnut Shrimp", "Big Plate Chicken", "Lion Head Meatballs", "Szechuan Fish"],
    booking: "Reservations recommended for dinner. Perfect for business lunches or celebrations.",
    reviews: [
        {name: "Yelp", rating: 5, text: "Traditional Roast Peking Duck. Thin, crispy skin with authentic preparation."},
        {name: "Website", rating: 5, text: "Michelin-Level Chinese in Palo Alto! Famous walnut shrimp and fiery Big Plate Chicken."}
    ],
    heroImage: "images/imperial-treasure-1.jpg",
    gallery: ["images/imperial-treasure-2.jpg", "images/imperial-treasure-3.jpg", "images/imperial-treasure-4.jpg"],
    michelin: 0
},
{
    id: 15,
    name: "R & G Lounge",
    location: "sf",
    status: "tried",
    occasion: "special",
    cuisine: "chinese",
    price: "$$$",
    rating: 4.3,
    reviewCount: 5373,
    tags: ["San Francisco", "Cantonese", "Seafood"],
    address: "631 Kearny St, San Francisco",
    phone: "(415) 982-7877",
    occasionLabel: "Family, Friends, Special",
    capacity: "2-12 people",
    dishes: ["Salt & Pepper Crab", "Peking Duck", "Garlic Steamed Lobster", "Soy Sauce Chicken"],
    booking: "Walk-in or reservations recommended. Large groups welcome. Basement dining room seats hundreds.",
    reviews: [
        {name: "Michelle L.", rating: 5, text: "Best Cantonese food in Chinatown! The salt & pepper crab is legendary. Perfect for family dinners."},
        {name: "David K.", rating: 5, text: "Huge portions, authentic flavors. Their Peking duck rivals restaurants in Hong Kong."},
        {name: "Jennifer W.", rating: 4, text: "Busy basement dining room, but worth the wait. Garlic lobster was incredible."}
    ],
    heroImage: "images/r-and-g-lounge-1.jpg",
    gallery: ["images/r-and-g-lounge-2.jpg", "images/r-and-g-lounge-3.jpg", "images/r-and-g-lounge-4.jpg"],
    michelin: 0,
    date: "2025-02-19"
},
{
    id: 16,
    name: "Sorrel",
    location: "sf",
    status: "tried",
    occasion: "special",
    cuisine: "italian",
    price: "$$$$$",
    rating: 4.0,
    reviewCount: 398,
    tags: ["San Francisco", "Italian", "Michelin ★"],
    address: "3228 Sacramento St, San Francisco",
    phone: "(415) 525-3765",
    occasionLabel: "Special, Date, Anniversary",
    capacity: "2-6 people",
    dishes: ["Handmade Pasta", "Miso Mustard King Salmon", "Squab with Black Garlic", "Sourdough Focaccia"],
    booking: "Reservations required. Tasting menu available. Wed-Sun dinner only.",
    reviews: [
        {name: "Michelle R.", rating: 5, text: "Michelin star worthy! The handmade pasta and locally sourced ingredients shine. Intimate setting."},
        {name: "James T.", rating: 5, text: "Seasonal menu changes weekly. King salmon with miso mustard was perfectly executed. Excellent wine pairings."},
        {name: "Sarah L.", rating: 4, text: "Chic minimalist space. The squab with black garlic and spring onion was exceptional. Pricey but memorable."}
    ],
    heroImage: "images/sorrel-1.jpg",
    gallery: ["images/sorrel-2.jpg", "images/sorrel-3.jpg", "images/sorrel-4.jpg"],
    michelin: 1,
    date: "2025-02-15"
}
];

// Export for use in main script
// Continue with more restaurants (17-24)
restaurantData.push(
{
    id: 17,
    name: "The French Laundry",
    location: "napa",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$$",
    rating: 4.8,
    reviewCount: 2100,
    tags: ["Yountville", "French", "Californian"],
    address: "6640 Washington St, Yountville",
    phone: "(707) 944-2380",
    occasionLabel: "Special, Anniversary, Celebration",
    capacity: "2-6 people",
    dishes: ["Chef's Tasting Menu", "Oysters and Pearls", "Macaroni and Cheese", "Coffee and Doughnuts"],
    booking: "Reservations open 2 months in advance. Book at 10am PT exactly. $350+ per person.",
    reviews: [
        {name: "Thomas K.", rating: 5, text: "Life-changing experience. Every course is perfection. Worth every penny and the months-long wait."},
        {name: "Michelin Guide", rating: 5, text: "Exceptional cuisine, worth a special journey. Thomas Keller's iconic restaurant sets the standard."},
        {name: "Sarah M.", rating: 5, text: "The service is impeccable. The garden vegetables are harvested daily. Pure culinary artistry."}
    ],
    heroImage: "images/the-french-laundry-1.jpg",
    gallery: ["images/the-french-laundry-2.jpg", "images/the-french-laundry-3.jpg", "images/the-french-laundry-4.jpg"],
    michelin: 3
},
{
    id: 18,
    name: "Kenzo",
    location: "napa",
    status: "togo",
    occasion: "special",
    cuisine: "japanese",
    price: "$$$$$",
    rating: 4.6,
    reviewCount: 380,
    tags: ["Napa", "Japanese", "Kaiseki"],
    address: "1339 Pearl St, Napa",
    phone: "(707) 294-2049",
    occasionLabel: "Special, Date, Omakase",
    capacity: "2-4 people",
    dishes: ["Kaiseki Menu", "Sashimi", "Wagyu", "Uni"],
    booking: "Reservations required. Limited seating. Counter seating available.",
    reviews: [
        {name: "David L.", rating: 5, text: "Authentic Japanese kaiseki in Napa. Ingredients flown daily from Japan. Exceptional."},
        {name: "Michelin Guide", rating: 5, text: "High quality cooking. Traditional techniques meet Napa Valley ingredients."}
    ],
    heroImage: "images/kenzo-1.jpg",
    gallery: ["images/kenzo-2.jpg", "images/kenzo-3.jpg", "images/kenzo-4.jpg"],
    michelin: 1
},
{
    id: 19,
    name: "Auberge du Soleil",
    location: "napa",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$",
    rating: 4.5,
    reviewCount: 850,
    tags: ["Rutherford", "French", "View"],
    address: "180 Rutherford Hill Rd, Rutherford",
    phone: "(800) 348-5406",
    occasionLabel: "Special, Date, Anniversary",
    capacity: "2-8 people",
    dishes: ["Chef's Tasting Menu", "Mediterranean Octopus", "Lamb", "Chocolate Soufflé"],
    booking: "Reservations recommended. Request terrace seating for views. Valet parking.",
    reviews: [
        {name: "Jennifer K.", rating: 5, text: "Stunning views of Napa Valley. Held Michelin star for 18 years. Unforgettable."},
        {name: "Robert M.", rating: 5, text: "The terrace dining is magical at sunset. Mediterranean flavors shine."}
    ],
    heroImage: "images/auberge-du-soleil-1.jpg",
    gallery: ["images/auberge-du-soleil-2.jpg", "images/auberge-du-soleil-3.jpg", "images/auberge-du-soleil-4.jpg"],
    michelin: 1
},
{
    id: 20,
    name: "Auro",
    location: "napa",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.4,
    reviewCount: 420,
    tags: ["Calistoga", "American", "Contemporary"],
    address: "400 Silverado Trail N, Calistoga",
    phone: "(707) 709-2160",
    occasionLabel: "Special, Date, Wine Tasting",
    capacity: "2-6 people",
    dishes: ["Japanese Shima Aji", "Black Trumpet Mushroom Tetela", "Valencia Orange Sherbet", "Cinnamon Churros"],
    booking: "Reservations required. Seven-course tasting menu. Wine pairings available.",
    reviews: [
        {name: "Lisa T.", rating: 5, text: "Chef Rogelio Garcia is brilliant. James Beard finalist. Seven courses of perfection."},
        {name: "Michael R.", rating: 5, text: "Wine pairings are exceptional. Over 475 labels. Monthly winery series dinners."}
    ],
    heroImage: "images/auro-1.jpg",
    gallery: ["images/auro-2.jpg", "images/auro-3.jpg", "images/auro-4.jpg"],
    michelin: 1
},
{
    id: 21,
    name: "PRESS",
    location: "napa",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 680,
    tags: ["St. Helena", "American", "Wine"],
    address: "587 St Helena Hwy, St Helena",
    phone: "(707) 967-0550",
    occasionLabel: "Special, Date, Wine Dinner",
    capacity: "2-8 people",
    dishes: ["Dry-Aged Ribeye", "Local Vegetables", "House-made Pasta", "Seasonal Dessert"],
    booking: "Reservations recommended. Wine cellar tours available. Request sommelier table.",
    reviews: [
        {name: "Wine Lover", rating: 5, text: "Largest Napa Valley wine collection in the world. 10,000 bottles. Grand Award winner."},
        {name: "James P.", rating: 5, text: "Multiple sommeliers on staff. Perfect pairings every time. Meat and pasta dishes shine."}
    ],
    heroImage: "images/press-1.jpg",
    gallery: ["images/press-2.jpg", "images/press-3.jpg", "images/press-4.jpg"],
    michelin: 1
},
{
    id: 22,
    name: "10 Butchers Korean BBQ",
    location: "bay-area",
    status: "togo",
    occasion: "casual",
    cuisine: "korean",
    price: "$$$",
    rating: 4.5,
    reviewCount: 2106,
    tags: ["Sunnyvale", "Korean BBQ", "Wagyu"],
    address: "595 E El Camino Real, Sunnyvale",
    phone: "(408) 720-8889",
    occasionLabel: "Casual, Friends, Family",
    capacity: "2-8 people",
    dishes: ["10 Cuts of Wagyu Beef", "Prime Ribeye", "Marinated Short Rib", "Hydro Stewed Soups"],
    booking: "Reservations recommended on weekends. Walk-ins welcome weekdays. Lunch and dinner service.",
    reviews: [
        {name: "Jennifer K.", rating: 5, text: "Best Korean BBQ in the Bay Area! Premium quality meat, beautiful modern interior. Worth every penny."},
        {name: "David L.", rating: 5, text: "The 10 different cuts of wagyu are incredible. Servers cook everything perfectly at the table."},
        {name: "Michelle R.", rating: 4, text: "Upscale Korean BBQ experience. Great for groups. Make reservations on weekends."}
    ],
    heroImage: "images/10-butchers-1.jpg",
    gallery: ["images/10-butchers-2.jpg", "images/10-butchers-3.jpg", "images/10-butchers-4.jpg"],
    michelin: 0
},
{
    id: 23,
    name: "Nursel",
    location: "bay-area",
    status: "togo",
    occasion: "casual",
    cuisine: "russian",
    price: "$$",
    rating: 4.5,
    reviewCount: 303,
    tags: ["San Carlos", "Central Asian", "Russian"],
    address: "601 Old County Rd, San Carlos",
    phone: "(650) 445-4075",
    occasionLabel: "Casual, Friends, Family",
    capacity: "2-6 people",
    dishes: ["Borsh", "Plov", "Manty", "Olivie Salad"],
    booking: "Walk-ins welcome. Across from San Carlos Caltrain. Pastries available for takeout.",
    reviews: [
        {name: "Jennifer L.", rating: 5, text: "Best borsh and olivie in the Bay Area! Authentic Kyrgyzstani flavors. Cozy family atmosphere."},
        {name: "David K.", rating: 5, text: "The plov has incredible aroma and flavors. A hidden gem in San Carlos. Try the pastries too!"},
        {name: "Michelle R.", rating: 4, text: "Unique Central Asian cuisine. Family-owned across from Caltrain. Great for a casual dinner."}
    ],
    heroImage: "images/nursel-1.jpg",
    gallery: ["images/nursel-2.jpg", "images/nursel-3.jpg", "images/nursel-4.jpg"],
    michelin: 0
},
{
    id: 24,
    name: "Daeho Kalbi Jjim & Beef Soup",
    location: "bay-area",
    status: "tried",
    occasion: "casual",
    cuisine: "korean",
    price: "$$",
    rating: 4.5,
    reviewCount: 1493,
    tags: ["Milpitas", "Korean", "Beef"],
    address: "217 W Calaveras Blvd, Milpitas",
    phone: "(408) 770-3778",
    occasionLabel: "Casual, Family, Friends",
    capacity: "2-6 people",
    dishes: ["Kalbi Jjim (Braised Beef Ribs)", "Kalbi Tang (Beef Rib Soup)", "Seolleong Tang", "Beef Tartare"],
    booking: "Walk-ins welcome. Expect wait during peak hours. Multiple locations in SF, Milpitas, San Mateo.",
    reviews: [
        {name: "Jennifer K.", rating: 5, text: "The kalbi jjim is incredible! Tender, flavorful, huge portions. Perfect for sharing."},
        {name: "David L.", rating: 5, text: "Best Korean beef soup in the Bay Area. The beef rib soup is comforting and rich."},
        {name: "Michelle R.", rating: 4, text: "Efficient setup, laid-back ambiance. Come hungry - portions are huge!"}
    ],
    heroImage: "images/daeho-milpitas-1.jpg",
    gallery: ["images/daeho-milpitas-2.jpg", "images/daeho-milpitas-3.jpg", "images/daeho-milpitas-4.jpg"],
    michelin: 0,
    date: "2025-03-01"
}
);

// Michelin-starred restaurants (25-66) - COMMENTED OUT until images are available
/*
restaurantData.push(
// === 3-STAR MICHELIN ===
{
    id: 25,
    name: "Atelier Crenn",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 972,
    tags: ["San Francisco", "French", "Michelin ★★★"],
    address: "3127 Fillmore St, San Francisco, CA 94123",
    phone: "(415) 440-0460",
    occasionLabel: "Special, Anniversary, Celebration",
    capacity: "2-4 people",
    dishes: ["Poetic Culinaria Tasting Menu", "Kir Breton", "Walk in the Forest", "Ocean Treasures", "Garden Vegetables"],
    booking: "Reservations required via Tock. Book well in advance. Tue-Sat dinner only.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Chef Dominique Crenn's poetic approach to cuisine results in extraordinary dishes that are both artistic and deeply flavorful."},
        {name: "Sarah L.", rating: 5, text: "A transcendent experience. Every course tells a story. Worth every penny for a once-in-a-lifetime meal."}
    ],
    heroImage: "images/atelier-crenn-1.jpg",
    gallery: ["images/atelier-crenn-2.jpg", "images/atelier-crenn-3.jpg", "images/atelier-crenn-4.jpg"],
    michelin: 3
},
{
    id: 26,
    name: "Quince",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "italian",
    price: "$$$$$",
    rating: 4.6,
    reviewCount: 1535,
    tags: ["San Francisco", "Italian", "Michelin ★★★"],
    address: "470 Pacific Ave, San Francisco, CA 94133",
    phone: "(415) 775-8500",
    occasionLabel: "Special, Anniversary, Celebration",
    capacity: "2-6 people",
    dishes: ["Nightly Tasting Menu", "Farm-to-Table Vegetables", "Handmade Pasta", "Tortellini en Brodo", "Seasonal Dessert"],
    booking: "Reservations required. Nightly-changing tasting menu from Fresh Run Farm partnership.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Chef Michael Tusk's Californian contemporary cuisine with Italian influences. Exclusive farm partnership yields extraordinary ingredients."},
        {name: "David M.", rating: 5, text: "Jackson Square gem. The farm-driven menu changes nightly and never disappoints. Impeccable service."}
    ],
    heroImage: "images/quince-1.jpg",
    gallery: ["images/quince-2.jpg", "images/quince-3.jpg", "images/quince-4.jpg"],
    michelin: 3
},
{
    id: 27,
    name: "SingleThread",
    location: "napa",
    status: "togo",
    occasion: "special",
    cuisine: "japanese",
    price: "$$$$$",
    rating: 4.8,
    reviewCount: 450,
    tags: ["Healdsburg", "Japanese-American", "Michelin ★★★"],
    address: "131 North St, Healdsburg, CA 95448",
    phone: "(707) 723-4646",
    occasionLabel: "Special, Anniversary, Getaway",
    capacity: "2-4 people",
    dishes: ["11-Course Kaiseki Menu", "Farm Vegetables", "Wagyu", "Seasonal Seafood", "Mochi Dessert"],
    booking: "Reservations required via Tock. 5 guest rooms available for overnight stay. Book months in advance.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Exceptional cuisine worth a special journey. Chef Kyle Connaughton's kaiseki-style menu draws from a 24-acre farm."},
        {name: "Michael R.", rating: 5, text: "World's 50 Best-listed. The farm-to-table concept taken to its absolute pinnacle. Unforgettable."}
    ],
    heroImage: "images/singlethread-1.jpg",
    gallery: ["images/singlethread-2.jpg", "images/singlethread-3.jpg", "images/singlethread-4.jpg"],
    michelin: 3
},
{
    id: 28,
    name: "Benu",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "asian",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 520,
    tags: ["San Francisco", "Asian-American", "Michelin ★★★"],
    address: "22 Hawthorne St, San Francisco, CA 94105",
    phone: "(415) 685-4860",
    occasionLabel: "Special, Anniversary, Celebration",
    capacity: "2-4 people",
    dishes: ["Fixed Tasting Menu", "Faux Shark Fin Soup", "Thousand-Year-Old Quail Egg", "Xiao Long Bao", "Seasonal Seafood"],
    booking: "Reservations required via Tock. Fixed menu each evening. Tue-Sat dinner only.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "First San Francisco restaurant to receive three Michelin stars. Chef Corey Lee's visionary Asian-American cuisine."},
        {name: "Jennifer K.", rating: 5, text: "Masterful blend of Asian techniques with modern innovation. The faux shark fin is legendary."}
    ],
    heroImage: "images/benu-1.jpg",
    gallery: ["images/benu-2.jpg", "images/benu-3.jpg", "images/benu-4.jpg"],
    michelin: 3
},
// === 2-STAR MICHELIN ===
{
    id: 29,
    name: "Californios",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "mexican",
    price: "$$$$$",
    rating: 4.6,
    reviewCount: 470,
    tags: ["San Francisco", "Mexican", "Michelin ★★"],
    address: "355 11th St, San Francisco, CA 94103",
    phone: "(415) 757-0994",
    occasionLabel: "Special, Date, Celebration",
    capacity: "2-4 people",
    dishes: ["Mexican Tasting Menu", "Mole", "Wagyu with Salsa", "Caviar Tostada", "Corn Dessert"],
    booking: "Reservations required via Tock. Upscale Mexican tasting menu. Book well in advance.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Excellent cooking worth a detour. Chef Val Cantu's elevated Mexican cuisine is groundbreaking."},
        {name: "Lisa T.", rating: 5, text: "Redefines Mexican fine dining. Every course is a revelation. The mole is life-changing."}
    ],
    heroImage: "images/californios-1.jpg",
    gallery: ["images/californios-2.jpg", "images/californios-3.jpg", "images/californios-4.jpg"],
    michelin: 2
},
{
    id: 30,
    name: "Commis",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 1214,
    tags: ["Oakland", "American", "Michelin ★★"],
    address: "3859 Piedmont Ave, Oakland, CA 94611",
    phone: "(510) 653-3902",
    occasionLabel: "Special, Date, Anniversary",
    capacity: "2-4 people",
    dishes: ["Seasonal Tasting Menu", "Poached Halibut", "Spring Pea Porridge", "Foraged Mushrooms", "Petit Fours"],
    booking: "Reservations required. Tue-Sun dinner. Oakland's only Michelin-starred restaurant.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Excellent cooking worth a detour. Chef James Syhabout's serene restaurant is packed every night."},
        {name: "Robert K.", rating: 5, text: "Oakland's crown jewel. Intimate, thoughtful, and absolutely delicious tasting menu."}
    ],
    heroImage: "images/commis-1.jpg",
    gallery: ["images/commis-2.jpg", "images/commis-3.jpg", "images/commis-4.jpg"],
    michelin: 2
},
{
    id: 31,
    name: "Lazy Bear",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 892,
    tags: ["San Francisco", "American", "Michelin ★★"],
    address: "3416 19th St, San Francisco, CA 94110",
    phone: "(415) 874-9921",
    occasionLabel: "Special, Date, Unique Experience",
    capacity: "2-4 people",
    dishes: ["Multi-Course Dinner Party", "Hearth-Cooked Meats", "Seasonal Vegetables", "Artisan Cheese", "House-Made Desserts"],
    booking: "Tickets via Tock. Communal dinner party format. Upstairs lounge for drinks first.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Excellent cooking worth a detour. Chef David Barzelay's dinner party concept is utterly unique."},
        {name: "Amanda R.", rating: 5, text: "Not just dinner — it's an experience. The communal format makes it unforgettable."}
    ],
    heroImage: "images/lazy-bear-1.jpg",
    gallery: ["images/lazy-bear-2.jpg", "images/lazy-bear-3.jpg", "images/lazy-bear-4.jpg"],
    michelin: 2
},
{
    id: 32,
    name: "Harbor House",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$$",
    rating: 4.8,
    reviewCount: 280,
    tags: ["Elk", "American", "Michelin ★★"],
    address: "5600 S Highway 1, Elk, CA 95432",
    phone: "(707) 877-3203",
    occasionLabel: "Special, Getaway, Anniversary",
    capacity: "2-4 people",
    dishes: ["Coastal Tasting Menu", "Pacific Seafood", "Foraged Ingredients", "Garden Vegetables", "Ocean-View Dessert"],
    booking: "Reservations required. 25-seat dining room above the Pacific. Inn rooms available.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Excellent cooking. Seasonality and weather shape the menu, relying on immediate surroundings."},
        {name: "Thomas K.", rating: 5, text: "Perched above the Pacific, this is California dining at its most elemental and beautiful."}
    ],
    heroImage: "images/harbor-house-1.jpg",
    gallery: ["images/harbor-house-2.jpg", "images/harbor-house-3.jpg", "images/harbor-house-4.jpg"],
    michelin: 2
},
{
    id: 33,
    name: "Saison",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 722,
    tags: ["San Francisco", "American", "Michelin ★★"],
    address: "178 Townsend St, San Francisco, CA 94107",
    phone: "(415) 828-7990",
    occasionLabel: "Special, Anniversary, Celebration",
    capacity: "2-6 people",
    dishes: ["Seasonal Tasting Menu", "Open-Fire Cooking", "Wagyu", "Caviar", "Artisan Desserts"],
    booking: "Reservations required via Tock. Tue-Sat dinner only. $300+ per person.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Excellent cooking worth a detour. Executive Chef Richard Lee delivers extraordinary Californian cuisine."},
        {name: "Mark W.", rating: 5, text: "Fire-driven cooking at its finest. Every ingredient is treated with reverence."}
    ],
    heroImage: "images/saison-1.jpg",
    gallery: ["images/saison-2.jpg", "images/saison-3.jpg", "images/saison-4.jpg"],
    michelin: 2
},
{
    id: 34,
    name: "Enclos",
    location: "napa",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$$",
    rating: 4.8,
    reviewCount: 37,
    tags: ["Sonoma", "French", "Michelin ★★"],
    address: "139 E Napa St, Sonoma, CA 95476",
    phone: "(707) 387-1724",
    occasionLabel: "Special, Date, Celebration",
    capacity: "2-4 people",
    dishes: ["Seasonal Tasting Menu", "French Techniques", "Wine Country Ingredients", "Artisan Bread", "Petit Fours"],
    booking: "Reservations required. Wed-Sat dinner only. Earned 2 stars within 6 months of opening.",
    reviews: [
        {name: "Eater SF", rating: 5, text: "Chef Brian Limoges burst onto the scene earning two Michelin stars within six months. Spectacular."},
        {name: "Jessica M.", rating: 5, text: "Sonoma's first Michelin recognition. Extraordinary seasonal cooking in an intimate setting."}
    ],
    heroImage: "images/enclos-1.jpg",
    gallery: ["images/enclos-2.jpg", "images/enclos-3.jpg", "images/enclos-4.jpg"],
    michelin: 2
},
{
    id: 35,
    name: "Kiln",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "european",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 121,
    tags: ["San Francisco", "European", "Michelin ★★"],
    address: "149 Fell St, San Francisco, CA 94102",
    phone: "(415) 982-9722",
    occasionLabel: "Special, Date, Anniversary",
    capacity: "2-4 people",
    dishes: ["Contemporary Tasting Menu", "Wood-Fired Dishes", "Seasonal Vegetables", "Artisan Cheese", "Elegant Desserts"],
    booking: "Reservations required. Tue-Sat dinner. Hayes Valley location.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Contemporary cooking at its finest. Michelin-starred industry veterans deliver exceptional cuisine."},
        {name: "David L.", rating: 5, text: "Hayes Valley's finest. Intimate space, incredible flavors, impeccable service."}
    ],
    heroImage: "images/kiln-1.jpg",
    gallery: ["images/kiln-2.jpg", "images/kiln-3.jpg", "images/kiln-4.jpg"],
    michelin: 2
},
// === 1-STAR MICHELIN ===
{
    id: 36,
    name: "7 Adams",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.7,
    reviewCount: 320,
    tags: ["San Francisco", "American", "Michelin ★"],
    address: "1963 Sutter St, San Francisco, CA 94115",
    phone: "(415) 655-9154",
    occasionLabel: "Special, Date, Anniversary",
    capacity: "2-4 people",
    dishes: ["5-Course Prix Fixe", "Seasonal Californian Dishes", "Handmade Pasta", "Local Seafood", "Artisan Dessert"],
    booking: "Reservations recommended. 5-course menu $87. Great value Michelin star.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Signature magic highlighting Californian simplicity with solid technique and thoughtful flavors."},
        {name: "Amy T.", rating: 5, text: "Best value Michelin star in SF. Chef David Fisher delivers magic in Pacific Heights."}
    ],
    heroImage: "images/7-adams-1.jpg",
    gallery: ["images/7-adams-2.jpg", "images/7-adams-3.jpg", "images/7-adams-4.jpg"],
    michelin: 1
},
{
    id: 37,
    name: "Angler",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "seafood",
    price: "$$$$",
    rating: 4.5,
    reviewCount: 752,
    tags: ["San Francisco", "Seafood", "Michelin ★"],
    address: "132 The Embarcadero, San Francisco, CA 94105",
    phone: "(415) 872-9442",
    occasionLabel: "Special, Date, Waterfront",
    capacity: "2-6 people",
    dishes: ["Wood-Fired Seafood", "Whole Grilled Fish", "Bay Shrimp", "Hearth-Roasted Vegetables", "Seasonal Dessert"],
    booking: "Reservations recommended. Embarcadero waterfront with bay views. Wood-burning hearth.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "High quality cooking worth a stop. Seafood-focused with views of the wood-burning hearth and SF Bay."},
        {name: "James P.", rating: 5, text: "From Saison Hospitality. The whole grilled fish over the hearth is extraordinary."}
    ],
    heroImage: "images/angler-1.jpg",
    gallery: ["images/angler-2.jpg", "images/angler-3.jpg", "images/angler-4.jpg"],
    michelin: 1
},
{
    id: 38,
    name: "Aubergine",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 373,
    tags: ["Carmel", "French", "Michelin ★"],
    address: "Monte Verde St & 7th Ave, Carmel-by-the-Sea, CA 93921",
    phone: "(831) 624-8578",
    occasionLabel: "Special, Getaway, Anniversary",
    capacity: "2-4 people",
    dishes: ["Tasting Menu", "Monterey Bay Seafood", "Local Produce", "French Technique", "Elegant Desserts"],
    booking: "Reservations required. Inside L'Auberge Carmel. Wed-Sun dinner only.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "High quality cooking. Beautifully presented dishes with tiny edible flowers and elegant sauces."},
        {name: "Sarah L.", rating: 5, text: "Michelin star and Forbes Five-Star. Impeccable service in charming Carmel setting."}
    ],
    heroImage: "images/aubergine-1.jpg",
    gallery: ["images/aubergine-2.jpg", "images/aubergine-3.jpg", "images/aubergine-4.jpg"],
    michelin: 1
},
{
    id: 39,
    name: "Bar Crenn",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 173,
    tags: ["San Francisco", "French", "Michelin ★"],
    address: "3131 Fillmore St, San Francisco, CA 94123",
    phone: "(415) 440-0460",
    occasionLabel: "Special, Date, Wine Bar",
    capacity: "2-4 people",
    dishes: ["Le Comptoir Omakase", "French Small Plates", "Artisan Cocktails", "Wine Pairings", "Petit Fours"],
    booking: "Reservations for Le Comptoir via Tock. Lounge walk-ins welcome. Tue-Sat.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "French omakase counter with twelve inventive small plates and bespoke pairings."},
        {name: "Nicole R.", rating: 5, text: "Sister to Atelier Crenn. The counter experience is intimate and magical."}
    ],
    heroImage: "images/bar-crenn-1.jpg",
    gallery: ["images/bar-crenn-2.jpg", "images/bar-crenn-3.jpg", "images/bar-crenn-4.jpg"],
    michelin: 1
},
{
    id: 40,
    name: "Birdsong",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 486,
    tags: ["San Francisco", "American", "Michelin ★"],
    address: "1085 Mission St, San Francisco, CA 94103",
    phone: "(415) 369-6000",
    occasionLabel: "Special, Date, Anniversary",
    capacity: "2-4 people",
    dishes: ["Heritage Tasting Menu", "Fire-Cooked Meats", "Whole-Animal Butchery", "Foraged Ingredients", "Seasonal Dessert"],
    booking: "Reservations required. Tue-Sat dinner. Fire-driven heritage cuisine.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Heritage cuisine connecting present to natural habitat of the past. Whole ingredients cooked with respect."},
        {name: "Chris B.", rating: 5, text: "Chef Chris Bleidorn's fire-driven cooking is primal and refined simultaneously."}
    ],
    heroImage: "images/birdsong-1.jpg",
    gallery: ["images/birdsong-2.jpg", "images/birdsong-3.jpg", "images/birdsong-4.jpg"],
    michelin: 1
},
{
    id: 41,
    name: "Chez Noir",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$",
    rating: 4.7,
    reviewCount: 150,
    tags: ["Carmel", "French", "Michelin ★"],
    address: "5th Ave between Dolores & San Carlos St, Carmel-by-the-Sea, CA 93921",
    phone: "N/A",
    occasionLabel: "Special, Date, Getaway",
    capacity: "2-4 people",
    dishes: ["Seafood-Centric Menu", "Monterey Bay Fish", "Local Vegetables", "French Pastry", "Wine Pairings"],
    booking: "Reservations required via website. No phone. Intimate Carmel village setting.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Modern seafood-centric menu showcasing pristine ingredients from the Monterey Peninsula."},
        {name: "Michael T.", rating: 5, text: "A gem in Carmel. Spectacular wine pairings and beautifully prepared dishes."}
    ],
    heroImage: "images/chez-noir-1.jpg",
    gallery: ["images/chez-noir-2.jpg", "images/chez-noir-3.jpg", "images/chez-noir-4.jpg"],
    michelin: 1
},
{
    id: 42,
    name: "Cyrus",
    location: "napa",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 88,
    tags: ["Geyserville", "French", "Michelin ★"],
    address: "275 Highway 128, Geyserville, CA 95441",
    phone: "(707) 723-5999",
    occasionLabel: "Special, Wine Country, Anniversary",
    capacity: "2-4 people",
    dishes: ["Wine Country Tasting Menu", "French Technique", "Alexander Valley Views", "Seasonal Produce", "Artisan Desserts"],
    booking: "Reservations required. Panoramic views of Alexander Valley. Chef Douglas Keane.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "High quality cooking. This pastoral restaurant floats above the vines with panoramic views."},
        {name: "Steven R.", rating: 5, text: "Chef Douglas Keane's triumphant return. Wine Country dining at its absolute finest."}
    ],
    heroImage: "images/cyrus-1.jpg",
    gallery: ["images/cyrus-2.jpg", "images/cyrus-3.jpg", "images/cyrus-4.jpg"],
    michelin: 1
},
{
    id: 43,
    name: "Hilda and Jesse",
    location: "sf",
    status: "togo",
    occasion: "date",
    cuisine: "american",
    price: "$$$",
    rating: 4.5,
    reviewCount: 215,
    tags: ["San Francisco", "American", "Michelin ★"],
    address: "701 Union St, San Francisco, CA 94133",
    phone: "(415) 872-7023",
    occasionLabel: "Date, Brunch, Special",
    capacity: "2-4 people",
    dishes: ["Innovative American Dishes", "Seasonal Small Plates", "Brunch Specialties", "Creative Desserts", "Craft Cocktails"],
    booking: "Reservations recommended. North Beach location. Creative twists on classics.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Innovative approach to classic dishes with creative twists and quality seasonal ingredients."},
        {name: "Rachel W.", rating: 5, text: "High-quality cuisine at excellent value. Every dish is visually stunning and delicious."}
    ],
    heroImage: "images/hilda-and-jesse-1.jpg",
    gallery: ["images/hilda-and-jesse-2.jpg", "images/hilda-and-jesse-3.jpg", "images/hilda-and-jesse-4.jpg"],
    michelin: 1
},
{
    id: 44,
    name: "Kin Khao",
    location: "sf",
    status: "togo",
    occasion: "date",
    cuisine: "thai",
    price: "$$$",
    rating: 4.5,
    reviewCount: 2650,
    tags: ["San Francisco", "Thai", "Michelin ★"],
    address: "55 Cyril Magnin St, San Francisco, CA 94102",
    phone: "(415) 362-7456",
    occasionLabel: "Date, Casual, Friends",
    capacity: "2-6 people",
    dishes: ["Crispy Rice Salad", "Khao Soi", "Green Curry", "Pad Thai", "Thai Tea"],
    booking: "Reservations recommended. Inside Parc 55 Hilton. Corner of Mason & Ellis.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "High quality Thai cooking with Californian seasonal ingredients. Bold, authentic flavors."},
        {name: "Amy L.", rating: 5, text: "Best Thai in SF. The crispy rice salad is addictive. Great for groups."}
    ],
    heroImage: "images/kin-khao-1.jpg",
    gallery: ["images/kin-khao-2.jpg", "images/kin-khao-3.jpg", "images/kin-khao-4.jpg"],
    michelin: 1
},
{
    id: 45,
    name: "Localis",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 781,
    tags: ["Sacramento", "American", "Michelin ★"],
    address: "2031 S St, Sacramento, CA 95811",
    phone: "(916) 737-7699",
    occasionLabel: "Special, Date, Unique",
    capacity: "2-4 people",
    dishes: ["Rotating 5-Week Tasting Menu", "Farm-to-Fork", "Wine Pairings", "Counter Dining", "Artisan Desserts"],
    booking: "Reservations required via Tock. Menu changes entirely every 5 weeks. Wed-Sat dinner.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Creative, frequently changing menu with engaging counter experience. Sacramento's star."},
        {name: "Jennifer K.", rating: 5, text: "The rotating menu keeps you coming back. Award-winning wine list. Sacramento's pride."}
    ],
    heroImage: "images/localis-1.jpg",
    gallery: ["images/localis-2.jpg", "images/localis-3.jpg", "images/localis-4.jpg"],
    michelin: 1
},
{
    id: 46,
    name: "Madcap",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 427,
    tags: ["San Anselmo", "American", "Michelin ★"],
    address: "198 Sir Francis Drake Blvd, San Anselmo, CA 94960",
    phone: "(415) 453-9898",
    occasionLabel: "Special, Date, Marin",
    capacity: "2-4 people",
    dishes: ["Asian-Inspired Tasting Menu", "Seasonal Seafood", "Local Vegetables", "Handmade Ceramics", "Creative Desserts"],
    booking: "Reservations recommended. Marin County gem. Beautiful local ceramics.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Contemporary Asian-influenced cuisine. Attention to detail extends to locally crafted ceramics."},
        {name: "David R.", rating: 5, text: "A top-rate dining experience in lovely San Anselmo. Service and food both stellar."}
    ],
    heroImage: "images/madcap-1.jpg",
    gallery: ["images/madcap-2.jpg", "images/madcap-3.jpg", "images/madcap-4.jpg"],
    michelin: 1
},
{
    id: 47,
    name: "Mister Jiu's",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "chinese",
    price: "$$$$",
    rating: 4.5,
    reviewCount: 1141,
    tags: ["San Francisco", "Chinese-American", "Michelin ★"],
    address: "28 Waverly Pl, San Francisco, CA 94108",
    phone: "(415) 857-9688",
    occasionLabel: "Special, Date, Chinatown",
    capacity: "2-6 people",
    dishes: ["Smoked Quail", "Hot & Sour Soup", "Sesame Noodles", "Peking Duck", "Tea-Smoked Dessert"],
    booking: "Reservations via Resy. Chinatown's Waverly Place. Tue-Sat dinner.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Chef Brandon Jew's Californian take on Chinese cooking. Top-flight ingredients for original dishes."},
        {name: "Michelle T.", rating: 5, text: "Chinatown reimagined. The Peking duck and smoked quail are extraordinary."}
    ],
    heroImage: "images/mister-jius-1.jpg",
    gallery: ["images/mister-jius-2.jpg", "images/mister-jius-3.jpg", "images/mister-jius-4.jpg"],
    michelin: 1
},
{
    id: 48,
    name: "Nari",
    location: "sf",
    status: "togo",
    occasion: "date",
    cuisine: "thai",
    price: "$$$",
    rating: 4.5,
    reviewCount: 598,
    tags: ["San Francisco", "Thai", "Michelin ★"],
    address: "1625 Post St, San Francisco, CA 94115",
    phone: "(415) 868-6274",
    occasionLabel: "Date, Special, Japantown",
    capacity: "2-6 people",
    dishes: ["Isaan Sausage", "Khao Soi", "Crab Curry", "Thai Salads", "Coconut Dessert"],
    booking: "Reservations recommended. Inside Hotel Kabuki, Japantown. Chef Pim Techamuanvivit.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Bold and exciting Thai cuisine. Chef Pim Techamuanvivit brings authentic flavors to Japantown."},
        {name: "Alex P.", rating: 5, text: "Perfect date night spot. Bold flavors, beautiful setting in Hotel Kabuki."}
    ],
    heroImage: "images/nari-1.jpg",
    gallery: ["images/nari-2.jpg", "images/nari-3.jpg", "images/nari-4.jpg"],
    michelin: 1
},
{
    id: 49,
    name: "Niku Steakhouse",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "japanese",
    price: "$$$$$",
    rating: 4.6,
    reviewCount: 948,
    tags: ["San Francisco", "Japanese-American", "Michelin ★"],
    address: "61 Division St, San Francisco, CA 94103",
    phone: "(415) 829-7817",
    occasionLabel: "Special, Date, Steakhouse",
    capacity: "2-6 people",
    dishes: ["Japanese Wagyu", "Dry-Aged Steaks", "Uni Toast", "Wagyu Tartare", "Mochi Ice Cream"],
    booking: "Reservations required. Boutique steakhouse with Japanese influence. Sun-Sat dinner.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Modern American steakhouse with Japanese influence. Exceptional wagyu program."},
        {name: "Jennifer K.", rating: 5, text: "Premium wagyu and dry-aged beef. The uni toast starter is heavenly."}
    ],
    heroImage: "images/niku-steakhouse-1.jpg",
    gallery: ["images/niku-steakhouse-2.jpg", "images/niku-steakhouse-3.jpg", "images/niku-steakhouse-4.jpg"],
    michelin: 1
},
{
    id: 50,
    name: "Nisei",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "japanese",
    price: "$$$$",
    rating: 4.7,
    reviewCount: 174,
    tags: ["San Francisco", "Japanese-American", "Michelin ★"],
    address: "2316 Polk St, San Francisco, CA 94109",
    phone: "(415) 827-6898",
    occasionLabel: "Special, Date, Russian Hill",
    capacity: "2-4 people",
    dishes: ["Japanese-American Tasting Menu", "Seasonal Sashimi", "Farm Vegetables", "Wagyu", "Mochi Dessert"],
    booking: "Reservations required. Wed-Sun dinner. Chef David Yoshimura's journey as a second-gen Japanese American.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Young Chef Award winner. Japanese-American identity expressed through refined seasonal cooking."},
        {name: "Kelly M.", rating: 5, text: "Russian Hill gem. Chef Yoshimura's personal story shines through every course."}
    ],
    heroImage: "images/nisei-1.jpg",
    gallery: ["images/nisei-2.jpg", "images/nisei-3.jpg", "images/nisei-4.jpg"],
    michelin: 1
},
{
    id: 51,
    name: "O' by Claude Le Tohic",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$$",
    rating: 4.6,
    reviewCount: 239,
    tags: ["San Francisco", "French", "Michelin ★"],
    address: "165 O'Farrell St, 5th Floor, San Francisco, CA 94102",
    phone: "(415) 814-8888",
    occasionLabel: "Special, Date, French Fine Dining",
    capacity: "2-6 people",
    dishes: ["French Tasting Menu", "Water-Fire-Earth Elements", "Caviar Course", "Wagyu", "Grand Dessert"],
    booking: "Reservations required. 5th floor of ONE65. Tue-Sat dinner. Elegant setting.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Modern French cuisine based on elements of water, fire and earth. Luxurious but not pretentious."},
        {name: "Robert M.", rating: 5, text: "The crowning jewel of ONE65. Beautiful elegant restaurant with exceptional French cuisine."}
    ],
    heroImage: "images/o-by-claude-le-tohic-1.jpg",
    gallery: ["images/o-by-claude-le-tohic-2.jpg", "images/o-by-claude-le-tohic-3.jpg", "images/o-by-claude-le-tohic-4.jpg"],
    michelin: 1
},
{
    id: 52,
    name: "Plumed Horse",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 1467,
    tags: ["Saratoga", "American", "Michelin ★"],
    address: "14555 Big Basin Way, Saratoga, CA 95070",
    phone: "(408) 867-4711",
    occasionLabel: "Special, Date, Silicon Valley",
    capacity: "2-8 people",
    dishes: ["California Tasting Menu", "Black Pepper Parmesan Soufflé", "Uni & Blue Crab", "Wagyu", "Seasonal Dessert"],
    booking: "Reservations recommended. Open since 1952. 20,000-bottle wine cellar. Tue-Sun dinner.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Inventive upscale modern cooking. Décor exudes warmth in an elegant yet comfortable setting."},
        {name: "Lisa T.", rating: 5, text: "Silicon Valley's finest. Chef Peter Armellino's soufflé with uni is legendary."}
    ],
    heroImage: "images/plumed-horse-1.jpg",
    gallery: ["images/plumed-horse-2.jpg", "images/plumed-horse-3.jpg", "images/plumed-horse-4.jpg"],
    michelin: 1
},
{
    id: 53,
    name: "Protégé",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "french",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 543,
    tags: ["Palo Alto", "French", "Michelin ★"],
    address: "250 California Ave, Palo Alto, CA 94306",
    phone: "N/A",
    occasionLabel: "Special, Date, Silicon Valley",
    capacity: "2-6 people",
    dishes: ["Californian Tasting Menu", "French Technique", "Seasonal Fish", "Wagyu", "Petits Fours"],
    booking: "Reservations via Tock or email. No phone service. Book well in advance.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Contemporary Californian cuisine with French influences. Palo Alto's premier fine dining."},
        {name: "Kevin M.", rating: 5, text: "Former French Laundry team. Exceptional tasting menu in a polished Palo Alto setting."}
    ],
    heroImage: "images/protege-1.jpg",
    gallery: ["images/protege-2.jpg", "images/protege-3.jpg", "images/protege-4.jpg"],
    michelin: 1
},
{
    id: 54,
    name: "San Ho Won",
    location: "sf",
    status: "togo",
    occasion: "date",
    cuisine: "korean",
    price: "$$$",
    rating: 4.5,
    reviewCount: 883,
    tags: ["San Francisco", "Korean", "Michelin ★"],
    address: "2170 Bryant St, San Francisco, CA 94110",
    phone: "(415) 868-4479",
    occasionLabel: "Date, Friends, BBQ",
    capacity: "2-6 people",
    dishes: ["Korean Charcoal BBQ", "Galbi", "Japchae", "Kimchi Stew", "Seasonal Banchan"],
    booking: "Reservations recommended. Casual Korean BBQ in Mission District. Chef Corey Lee collaboration.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "High quality Korean charcoal BBQ. Collaboration between Corey Lee and Jeong-In Hwang."},
        {name: "David L.", rating: 5, text: "Casual but stellar. The BBQ quality rivals anything in Koreatown LA."}
    ],
    heroImage: "images/san-ho-won-1.jpg",
    gallery: ["images/san-ho-won-2.jpg", "images/san-ho-won-3.jpg", "images/san-ho-won-4.jpg"],
    michelin: 1
},
{
    id: 55,
    name: "Selby's",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 443,
    tags: ["Redwood City", "American", "Michelin ★"],
    address: "3001 El Camino Real, Redwood City, CA 94061",
    phone: "(650) 546-7700",
    occasionLabel: "Special, Date, Peninsula",
    capacity: "2-8 people",
    dishes: ["Beef Wellington", "Caviar Service", "Seasonal Fish", "Classic Cocktails", "Grand Dessert"],
    booking: "Reservations recommended. Open 7 nights. Chef Mark Sullivan. Walk-ins welcome.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Modern American cuisine with classic European influences. Timeless elegance in Redwood City."},
        {name: "Jennifer K.", rating: 5, text: "The Beef Wellington is phenomenal. Old-world glamour with modern cooking."}
    ],
    heroImage: "images/selbys-1.jpg",
    gallery: ["images/selbys-2.jpg", "images/selbys-3.jpg", "images/selbys-4.jpg"],
    michelin: 1
},
{
    id: 56,
    name: "Six Test Kitchen",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.8,
    reviewCount: 95,
    tags: ["Paso Robles", "American", "Michelin ★"],
    address: "3005 Limestone Way, Paso Robles, CA 93446",
    phone: "N/A",
    occasionLabel: "Special, Wine Country, Unique",
    capacity: "2-4 people",
    dishes: ["Multi-Course Tasting Menu", "Wine Country Ingredients", "Seasonal Produce", "Artisan Bread", "Creative Desserts"],
    booking: "Reservations required via website. No walk-ins. Book 2-3 months in advance. Tin City location.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "High quality cooking. Started in a garage, now Paso Robles' first Michelin star."},
        {name: "Michael R.", rating: 5, text: "Chef Ricky Odbert's counter dining in Tin City is intimate, creative, and extraordinary."}
    ],
    heroImage: "images/six-test-kitchen-1.jpg",
    gallery: ["images/six-test-kitchen-2.jpg", "images/six-test-kitchen-3.jpg", "images/six-test-kitchen-4.jpg"],
    michelin: 1
},
{
    id: 57,
    name: "Sons & Daughters",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 828,
    tags: ["San Francisco", "American", "Michelin ★"],
    address: "2875 18th St, San Francisco, CA 94110",
    phone: "(415) 391-8311",
    occasionLabel: "Special, Date, Anniversary",
    capacity: "2-4 people",
    dishes: ["New Nordic Tasting Menu", "Seasonal Vegetables", "Pacific Seafood", "Fermented Ingredients", "Artisan Desserts"],
    booking: "Reservations required. Mission District. Chefs Teague Moriarty and Matt McNamara.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Excellent cooking. New Nordic-influenced cuisine with Californian ingredients."},
        {name: "Sarah L.", rating: 5, text: "Intimate and personal. The seasonal tasting menu is always surprising and delightful."}
    ],
    heroImage: "images/sons-and-daughters-1.jpg",
    gallery: ["images/sons-and-daughters-2.jpg", "images/sons-and-daughters-3.jpg", "images/sons-and-daughters-4.jpg"],
    michelin: 1
},
{
    id: 58,
    name: "Ssal",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "korean",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 120,
    tags: ["San Francisco", "Korean", "Michelin ★"],
    address: "2226 Polk St, San Francisco, CA 94109",
    phone: "(415) 525-3765",
    occasionLabel: "Special, Date, Intimate",
    capacity: "2-4 people",
    dishes: ["Korean Tasting Menu", "Seasonal Banchan", "Rice Dishes", "Fermented Flavors", "Korean Dessert"],
    booking: "Reservations required. Small minimalist space on Polk Street. Very limited seating.",
    reviews: [
        {name: "SF Chronicle", rating: 5, text: "Hyunyoung and Junsoo Bae run their contemporary Korean restaurant in a small, minimalist space."},
        {name: "Amy L.", rating: 5, text: "Intimate and personal Korean fine dining. Every dish is precise and beautiful."}
    ],
    heroImage: "images/ssal-1.jpg",
    gallery: ["images/ssal-2.jpg", "images/ssal-3.jpg", "images/ssal-4.jpg"],
    michelin: 1
},
{
    id: 59,
    name: "State Bird Provisions",
    location: "sf",
    status: "togo",
    occasion: "date",
    cuisine: "american",
    price: "$$$",
    rating: 4.5,
    reviewCount: 3531,
    tags: ["San Francisco", "American", "Michelin ★"],
    address: "1529 Fillmore St, San Francisco, CA 94115",
    phone: "(415) 795-1272",
    occasionLabel: "Date, Friends, Casual Fine Dining",
    capacity: "2-6 people",
    dishes: ["State Bird with Provisions", "Dim Sum-Style Cart Service", "Seasonal Small Plates", "Pancake with Burrata", "Creative Desserts"],
    booking: "Reservations highly recommended. Dim sum-style cart service. Mon-Sat dinner.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "James Beard Award winner. Adventurous, inventive, and delicious contemporary American."},
        {name: "Lisa T.", rating: 5, text: "The cart service is so fun! Every plate is a surprise. Don't miss the state bird quail."}
    ],
    heroImage: "images/state-bird-provisions-1.jpg",
    gallery: ["images/state-bird-provisions-2.jpg", "images/state-bird-provisions-3.jpg", "images/state-bird-provisions-4.jpg"],
    michelin: 1
},
{
    id: 60,
    name: "Sun Moon Studio",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "japanese",
    price: "$$$$",
    rating: 4.8,
    reviewCount: 33,
    tags: ["Oakland", "Japanese", "Michelin ★"],
    address: "1940 Union St, Ste 21, Oakland, CA 94607",
    phone: "(510) 947-4178",
    occasionLabel: "Special, Intimate, Unique",
    capacity: "2-4 people",
    dishes: ["Omakase Menu", "Seasonal Seafood", "Japanese-Californian Fusion", "Handcrafted Dishes", "Tea Dessert"],
    booking: "Reservations required. Only 4 tables. Thu-Sun dinner. Former Benu chefs.",
    reviews: [
        {name: "SF Chronicle", rating: 5, text: "Alan Hsu and Sarah Cooper quietly opened with just four tables. Pedigree includes Benu and top Michelin restaurants."},
        {name: "Michelin Guide", rating: 5, text: "A clandestine air prevails but the secret is out: seats are hotly in demand. NEW 2025 star."}
    ],
    heroImage: "images/sun-moon-studio-1.jpg",
    gallery: ["images/sun-moon-studio-2.jpg", "images/sun-moon-studio-3.jpg", "images/sun-moon-studio-4.jpg"],
    michelin: 1
},
{
    id: 61,
    name: "The Kitchen",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.6,
    reviewCount: 1205,
    tags: ["Sacramento", "American", "Michelin ★"],
    address: "915 Broadway, Ste 100, Sacramento, CA 95818",
    phone: "(916) 568-7171",
    occasionLabel: "Special, Date, Sacramento",
    capacity: "2-6 people",
    dishes: ["6-Course Prix Fixe", "Farm-to-Fork", "Interactive Kitchen", "Wine Pairings", "Grand Dessert"],
    booking: "Reservations required. Wed-Sat dinner. Interactive open kitchen format since 1991.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Farm-to-fork dining at its best. Six-course prix fixe with the freshest local and regional ingredients."},
        {name: "Thomas K.", rating: 5, text: "Sacramento's original farm-to-fork. The interactive format makes every dinner an event."}
    ],
    heroImage: "images/the-kitchen-1.jpg",
    gallery: ["images/the-kitchen-2.jpg", "images/the-kitchen-3.jpg", "images/the-kitchen-4.jpg"],
    michelin: 1
},
{
    id: 62,
    name: "The Progress",
    location: "sf",
    status: "togo",
    occasion: "date",
    cuisine: "american",
    price: "$$$",
    rating: 4.5,
    reviewCount: 1324,
    tags: ["San Francisco", "American", "Michelin ★"],
    address: "1525 Fillmore St, San Francisco, CA 94115",
    phone: "(415) 673-1294",
    occasionLabel: "Date, Friends, Family-Style",
    capacity: "2-8 people",
    dishes: ["Family-Style Sharing Menu", "Seasonal Vegetables", "Duck for the Table", "Creative Small Plates", "Dessert Spread"],
    booking: "Reservations recommended. Sister to State Bird Provisions. Mon-Sat dinner.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Californian cuisine. Chefs Stuart Brioza and Nicole Krasinski deliver creative family-style dining."},
        {name: "Rachel W.", rating: 5, text: "Perfect for sharing. The duck and seasonal dishes are always outstanding."}
    ],
    heroImage: "images/the-progress-1.jpg",
    gallery: ["images/the-progress-2.jpg", "images/the-progress-3.jpg", "images/the-progress-4.jpg"],
    michelin: 1
},
{
    id: 63,
    name: "The Restaurant at JUSTIN",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$$",
    rating: 4.7,
    reviewCount: 104,
    tags: ["Paso Robles", "American", "Michelin ★"],
    address: "11680 Chimney Rock Rd, Paso Robles, CA 93446",
    phone: "(805) 591-3224",
    occasionLabel: "Special, Wine Country, Getaway",
    capacity: "2-6 people",
    dishes: ["Wine Country Tasting Menu", "Estate Wine Pairings", "Farm-to-Table", "Vineyard Vegetables", "Grand Dessert"],
    booking: "Reservations required. Only US winery with Michelin star + vineyard views.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Farm-to-table tasting menu paired with estate wines in a stunning vineyard setting."},
        {name: "Lisa T.", rating: 5, text: "The only Michelin-starred winery restaurant in the US. Wine pairings are perfection."}
    ],
    heroImage: "images/the-restaurant-at-justin-1.jpg",
    gallery: ["images/the-restaurant-at-justin-2.jpg", "images/the-restaurant-at-justin-3.jpg", "images/the-restaurant-at-justin-4.jpg"],
    michelin: 1
},
{
    id: 64,
    name: "The Shota",
    location: "sf",
    status: "togo",
    occasion: "special",
    cuisine: "japanese",
    price: "$$$$$",
    rating: 4.7,
    reviewCount: 321,
    tags: ["San Francisco", "Japanese", "Michelin ★"],
    address: "115 Sansome St, San Francisco, CA 94104",
    phone: "(628) 224-2074",
    occasionLabel: "Special, Date, Omakase",
    capacity: "2-4 people",
    dishes: ["Edomae Omakase", "Otsumami", "Seasonal Nigiri", "Wagyu", "Japanese Dessert"],
    booking: "Reservations required via website. Edomae-style omakase and kaiseki-inspired dishes.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Top quality ingredients with distinct flavours carefully prepared to a consistently high standard."},
        {name: "Kevin T.", rating: 5, text: "Financial District gem. The omakase is precise, elegant, and memorable."}
    ],
    heroImage: "images/the-shota-1.jpg",
    gallery: ["images/the-shota-2.jpg", "images/the-shota-3.jpg", "images/the-shota-4.jpg"],
    michelin: 1
},
{
    id: 65,
    name: "The Village Pub",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "american",
    price: "$$$",
    rating: 4.5,
    reviewCount: 1384,
    tags: ["Woodside", "American", "Michelin ★"],
    address: "2967 Woodside Rd, Woodside, CA 94062",
    phone: "(650) 851-9888",
    occasionLabel: "Special, Date, Peninsula",
    capacity: "2-8 people",
    dishes: ["California-French Menu", "Organic Farm Produce", "Seasonal Fish", "Wagyu Burger", "Artisan Dessert"],
    booking: "Reservations recommended. 80% produce from nearby organic farm. Mon-Sat.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Hyper-local California fare with French and Mediterranean twists. Approachable Michelin star."},
        {name: "Amanda P.", rating: 5, text: "Peninsula's best. The farm-driven menu in the cozy Woodside setting is perfection."}
    ],
    heroImage: "images/the-village-pub-1.jpg",
    gallery: ["images/the-village-pub-2.jpg", "images/the-village-pub-3.jpg", "images/the-village-pub-4.jpg"],
    michelin: 1
},
{
    id: 66,
    name: "Wakuriya",
    location: "bay-area",
    status: "togo",
    occasion: "special",
    cuisine: "japanese",
    price: "$$$$",
    rating: 4.7,
    reviewCount: 605,
    tags: ["San Mateo", "Japanese", "Michelin ★"],
    address: "115 De Anza Blvd, San Mateo, CA 94402",
    phone: "(650) 286-0410",
    occasionLabel: "Special, Date, Kaiseki",
    capacity: "2-4 people",
    dishes: ["Kaiseki Menu", "Seasonal Sashimi", "Wagyu", "Japanese Vegetables", "Matcha Dessert"],
    booking: "Reservations by phone only. Book 1 month in advance. One chef, intimate setting.",
    reviews: [
        {name: "Michelin Guide", rating: 5, text: "Innovative kaiseki blending deep respect for tradition with a contemporary touch. One chef behind the counter."},
        {name: "Sarah M.", rating: 5, text: "Chef Katsuhiro Yamasaki is a master. Intimate, personal, and utterly exquisite kaiseki."}
    ],
    heroImage: "images/wakuriya-1.jpg",
    gallery: ["images/wakuriya-2.jpg", "images/wakuriya-3.jpg", "images/wakuriya-4.jpg"],
    michelin: 1
}
);

// Export for use in main script
*/
window.restaurantData = restaurantData;
